version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing Node.js version 20 ...
  pre_build:
    commands:
      - echo Downgrading react to version 18.x ...
      - npm install react@18 react-dom@18 --save
      - echo Installing dependencies ...
      - npm install
  build:
    commands:
      - echo Building the app ...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
